// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace ST10404431CLDV6211POE.Models;

public partial class Booking
{
    [Key]
    public int BookingID { get; set; }

    [Required]
    [StringLength(50)]
    [Unicode(false)]
    public string EventID { get; set; }

    [Required]
    [StringLength(10)]
    [Unicode(false)]
    public string VenueID { get; set; }

    [Column(TypeName = "date")]
    public DateTime BookingDate { get; set; }

    [ForeignKey("EventID")]
    [InverseProperty("Bookings")]
    public virtual Event Event { get; set; }

    [ForeignKey("VenueID")]
    [InverseProperty("Bookings")]
    public virtual Venue Venue { get; set; }
}