// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ST10404431CLDV6211POE.Models;

public partial class Event
{
    public string EventID { get; set; }

    public string VenueID { get; set; }

    public string EventName { get; set; }

    public DateTime EventDate { get; set; }

    public string Description { get; set; }

    public virtual Venue Venue { get; set; }
}