// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace ST10404431CLDV6211POE.Models;

public partial class Event
{
    [Key]
    [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
    public string EventID { get; set; }

    [Required]
    [StringLength(10)]
    [Unicode(false)]
    public string VenueID { get; set; }

    [Required]
    [StringLength(50)]
    [Unicode(false)]
    public string EventName { get; set; }

    [Column(TypeName = "date")]
    public DateTime EventDate { get; set; }

    [Column(TypeName = "text")]
    public string Description { get; set; }

    [InverseProperty("Event")]
    public virtual ICollection<Booking> Bookings { get; set; } = new List<Booking>();

    [ForeignKey("VenueID")]
    [InverseProperty("Events")]
    public virtual Venue Venue { get; set; }
}